BEGIN;

-- Article 1: چگونه کودکان را به خواندن علاقه‌مند کنیم؟
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>The Importance of Reading in Childhood</h2><p>Reading is one of the most fundamental skills children learn during primary school. Building a reading habit early not only helps with academic progress but also keeps a child''s mind open and curious.</p><h2>Practical Methods</h2><p>First, create a suitable reading environment. A quiet corner with good lighting and colorful books can attract children to read. Parents should also model reading themselves — children whose parents read books are more likely to adopt the habit.</p><p>Choosing books appropriate to the child''s age and interests is very important. Short stories, picture books, and children''s magazines can be great starting points.</p><h2>Conclusion</h2><p>Be patient and encourage the child. Every page read is an achievement.</p>',
  'ps', '<h2>د ماشوموالي پر مهال د لوستلو اهمیت</h2><p>لوستل یو له بنسټیزو مهارتونو دی چې ماشومان د لومړني ښوونځي پر مهال زده کوي. د لوستلو عادت د پیل له وخته جوړول نه یوازې د تحصیلي پرمختګ سره مرسته کوي، بلکې د ماشوم ذهن هم خلاص او کنجکاو ساتي.</p><h2>عملي میتودونه</h2><p>لومړی، د لوستلو لپاره مناسب چاپیریال جوړ کړئ. یو چوپ ګوښه چې کافي رڼا او رنګارنګ کتابونه ولري کولای شي ماشومان لوستلو ته راوبولي. مور او پلار باید پخپله د لوستلو نمونه وي.</p><h2>پایله</h2><p>صبر وکړئ او ماشوم هڅوئ. هره پاڼه چې ولولي یوه بریا ده.</p>'
) WHERE id = 1;

-- Article 2: اشتباهات رایج در یادگیری الفبای دری
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Introduction</h2><p>Learning the alphabet is the first step in the journey of learning the Dari language. However, many children and even teachers face challenges at this stage.</p><h2>Mistake 1: Learning Letters Without Logical Order</h2><p>Many teachers teach letters in alphabetical order, but research shows that grouping letters by similar shape is far more effective.</p><h2>Mistake 2: Excessive Focus on Memorization Without Understanding</h2><p>Children need to understand that each letter has a sound. Connecting letters to familiar images and sounds is very helpful.</p><h2>Mistake 3: Lack of Sufficient Repetition</h2><p>Daily repetition, even just 15 minutes, has much more impact than long weekly sessions.</p>',
  'ps', '<h2>پیل</h2><p>د الفبا زده کول د دري ژبې د زده کړې سفر کې لومړی ګام دی. خو ډیر ماشومان او حتی ښوونکي پدې مرحله کې له ستونزو سره مخ کیږي.</p><h2>لومړۍ غلطي: د منطقي ترتیب پرته د توريو زده کول</h2><p>ډیر ښوونکي توري د الفبا پر ترتیب سره ښوي، خو څیړنې ښیي چې د ورته بڼې له مخې د توريو ډله بندي خورا ګټوره ده.</p><h2>دویمه غلطي: د پوهیدو پرته پر حفظ ډیر ټینګار</h2><p>ماشوم باید وپوهیږي چې هر توری یو غږ لري. توري له آشنا انځورونو او غږونو سره وصلول خورا ګټور دي.</p><h2>دریمه غلطي: د کافي تکرار نشتوالی</h2><p>ورځني تکرار، حتی یوازې ۱۵ دقیقې، د اونیزو اوږدو ناستو تر ډیرو اغیزناک دی.</p>'
) WHERE id = 2;

-- Article 3: روش‌های آموزش جدول ضرب به کودکان
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Why Is the Multiplication Table Important?</h2><p>The multiplication table is the foundation of all future mathematical calculations. A student who knows the multiplication table well will advance with more confidence in higher grades.</p><h2>Method 1: Songs and Rhythm</h2><p>Turning the multiplication table into a song is one of the most effective methods. Children''s minds retain music far better than dry numbers.</p><h2>Method 2: Card Games</h2><p>Make multiplication cards and play for a few minutes each day. This method entertains children while registering numbers in their minds.</p><h2>Method 3: Visual Patterns</h2><p>For example, the 5 multiplication table always ends in 0 or 5. Show children these patterns so they understand mathematical logic.</p><h2>Important Note</h2><p>Never force a child into rote memorization. Understanding the logic of multiplication is more important than memorizing.</p>',
  'ps', '<h2>ولې د ضرب جدول مهم دی؟</h2><p>د ضرب جدول د راتلونکو ټولو ریاضي محاسبو بنسټ دی. هغه زده کوونکی چې د ضرب جدول ښه پیژني، پورته صنفونو کې له ډیره باوره مخ کيږي.</p><h2>لومړی میتود: سندرې او ریتم</h2><p>د ضرب جدول سندرې ته بدلول یو له اغیزناکو میتودونو دی. د ماشومانو ذهن موسیقي تر وچو شمیرو ډیره ښه ساتي.</p><h2>دویم میتود: د کارت لوبې</h2><p>د ضرب کارتونه جوړ کړئ او هره ورځ یو څو دقیقې لوبه وکړئ. دا میتود ماشوم خوشاله کوي او شمیرې یې ذهن ته ثبتوي.</p><h2>دریم میتود: لیداري نمونې</h2><p>د بیلګې په توګه، د ۵ ضرب جدول تل ۰ یا ۵ ته ختمیږي. دا نمونې ماشومانو ته وښایاست ترڅو د ریاضي منطق پوه شي.</p><h2>مهمه یادونه</h2><p>هیڅکله ماشوم حبري حفظ ته مجبور مکړئ. د ضرب د منطق پوهیدل تر حفظولو مهم دي.</p>'
) WHERE id = 3;

-- Article 4: ریاضی را با بازی یاد بگیریم
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Math Through Play</h2><p>Play is the natural language of children. Integrating math into daily games makes learning enjoyable and lasting. Children learn best when they are having fun.</p><h2>Practical Ideas</h2><p>You can use dice games, card games, cooking measurements, grocery shopping, and board games to teach basic math concepts. Counting steps, measuring ingredients, and calculating change are all real-life math lessons.</p><h2>Benefits of Game-Based Learning</h2><p>Game-based learning reduces math anxiety, increases motivation, and builds a positive attitude toward the subject. Children who play math games tend to perform better in school.</p><h2>Conclusion</h2><p>Turn everyday moments into math opportunities. The kitchen, the market, and the playground are all classrooms.</p>',
  'ps', '<h2>د لوبې له لارې ریاضي زده کړه</h2><p>لوبه د ماشومانو طبیعي ژبه ده. د ریاضي د ورځنیو لوبو سره یوځای کول د زده کړه خوند لرونکې او پایښتنده کوي. ماشومان هغه وخت غوره زده کوي چې خوشاله وي.</p><h2>عملي نظرونه</h2><p>تاسو کولای شئ د ریاضي لومړنیو مفاهیمو د ښوولو لپاره د ډایس لوبې، د کارت لوبې، د پخلي اندازه ګیرۍ، بازار ته تګ، او بورډ لوبې وکاروئ.</p><h2>د لوبې پر بنسټ زده کړې ګټې</h2><p>د لوبې پر بنسټ زده کړه د ریاضي اضطراب کموي، هڅونه زیاتوي، او د مضمون سره مثبت چلند جوړوي.</p><h2>پایله</h2><p>ورځنۍ شیبې ریاضي فرصتونو ته واړوئ. پخلنځی، بازار، او لوبغالی ټول ښوونځي دي.</p>'
) WHERE id = 4;

-- Article 5: آزمایش‌های علمی ساده برای کودکان ابتدایی
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Science Experiments at Home</h2><p>Simple science experiments spark curiosity and teach children to observe, hypothesize, and draw conclusions. The best part is that most can be done with household items.</p><h2>Experiment 1: Volcano with Baking Soda</h2><p>Mix baking soda and vinegar to create a bubbling reaction. This demonstrates acid-base chemistry in a fun way.</p><h2>Experiment 2: Rainbow in a Glass</h2><p>Layer different liquids of varying densities like honey, oil, and water to create a colorful density column.</p><h2>Experiment 3: Growing Seeds</h2><p>Plant seeds in clear cups to observe root growth. This teaches biology basics and the importance of sunlight and water.</p><h2>Conclusion</h2><p>Science is everywhere. Help children discover it in their everyday environment.</p>',
  'ps', '<h2>د کور ساینسي آزمایښتونه</h2><p>ساده ساینسي آزمایښتونه د ماشومانو کنجکاوي بلوي او ورته لیدل، فرضیه جوړول، او پایلې ایستل ښوي. غوره برخه داده چې ډیری یې د کورني وسایلو سره کیدای شي.</p><h2>لومړی آزمایښت: د بیکینګ سوډا اتش فشان</h2><p>بیکینګ سوډا او سرکه سره یوځای کړئ ترڅو د بلبلیدو عکس العمل رامنځته شي. دا د اسید-بیس کیمیا د خوند لرونکي لارې نندارتیا کوي.</p><h2>دویم آزمایښت: د شیشې کې قوس قزح</h2><p>د ثقل د توپیر لرونکي مایعات لکه شات، تیل، او اوبه یو بل پسې واچوئ ترڅو رنګارنګ ستنه جوړه شي.</p><h2>دریم آزمایښت: د تخمونو کرل</h2><p>تخمونه د شفافه پیالو کې وکرئ ترڅو د ریښو وده ووینئ. دا د بیولوژۍ بنسټونه او د لمر او اوبو اهمیت ښوي.</p><h2>پایله</h2><p>ساینس هرچیرې دی. ماشومانو سره مرسته وکړئ چې یې خپل ورځني چاپیریال کې وموندلای شي.</p>'
) WHERE id = 5;

-- Article 6: روش صحیح آموزش تجوید به کودکان
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Introduction to Tajweed</h2><p>Tajweed refers to the rules of Quranic recitation. Teaching it to children requires patience, repetition, and making it enjoyable.</p><h2>Step 1: Start with Basic Letters</h2><p>Begin with the Arabic alphabet and their correct pronunciation. Focus on sounds that differ from everyday speech, such as the heavy and light letters.</p><h2>Step 2: Use Audio Examples</h2><p>Let children listen to skilled reciters. Imitation is one of the most powerful learning tools for young learners.</p><h2>Step 3: Short Daily Practice</h2><p>Fifteen minutes of daily practice is far more effective than an hour-long weekly session. Consistency is key.</p><h2>Conclusion</h2><p>With patience and encouragement, children can learn beautiful Quranic recitation.</p>',
  'ps', '<h2>د تجوید پیژندنه</h2><p>تجوید د قراني تلاوت مقررو ته وايي. د ماشومانو ته یې ښوول صبر، تکرار، او خوندوره کول غواړي.</p><h2>لومړی ګام: له بنسټیزو توريو پیل کول</h2><p>له عربي الفبا او د دوی سمو تلفظونو سره پیل وکړئ. پر غږونو چې له ورځني ژبو توپیر لري تمرکز وکړئ.</p><h2>دویم ګام: د غږ نمونو کارول</h2><p>ماشومانو ته د ماهر قاریانو غږ واورئ. تقلید د کوچنیو زده کوونکو لپاره یو له پیاوړو زده کړیزو وسیلو دی.</p><h2>دریم ګام: لنډ ورځني تمرین</h2><p>د ۱۵ دقیقو ورځنی تمرین د اونیز یوه ساعت ناستې تر خورا اغیزناک دی. دوام کلیدي دی.</p><h2>پایله</h2><p>د صبر او هڅونې سره ماشومان کولای شي ښکلی قراني تلاوت زده کړي.</p>'
) WHERE id = 6;

-- Article 7: راهنمای حل معادلات خطی برای پایه هفتم
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>What Is a Linear Equation?</h2><p>A linear equation is an equation where the variable appears with a power of 1. Solving these equations is a core skill in 7th grade math.</p><h2>Step-by-Step Method</h2><p>First, simplify both sides. Then move variable terms to one side and constants to the other. Finally, divide both sides by the coefficient of the variable.</p><h2>Example</h2><p>Solve: 2x + 5 = 13. Subtract 5 from both sides: 2x = 8. Divide by 2: x = 4.</p><h2>Practice Problems</h2><p>Regular practice with varied problems builds confidence and fluency. Start simple and gradually increase difficulty.</p><h2>Conclusion</h2><p>Linear equations are the gateway to algebra. Mastering them opens doors to advanced mathematics.</p>',
  'ps', '<h2>خطي معادله ولې ده؟</h2><p>خطي معادله هغه معادله ده چیرې چې متغیر د ۱ ځواک سره راشي. دا معادلې حل کول د ۷م ټولګي ریاضي کې یو بنسټیز مهارت دی.</p><h2>د ګام پر ګام میتود</h2><p>لومړی، دواړه خواوې ساده کړئ. بیا د متغیر جملې یوې خوا ته او ثابتونه بلې خوا ته لیږئ. پای کې دواړه خواوې د متغیر ضریب باندې ووهئ.</p><h2>بیلګه</h2><p>حل کړئ: 2x + 5 = 13. له دواړو خواوو 5 کم کړئ: 2x = 8. پر 2 ووهئ: x = 4.</p><h2>پایله</h2><p>خطي معادلې د الجبر دروازه ده. د دوی تسلط پرمختللي ریاضي ته دروازې پرانیزي.</p>'
) WHERE id = 7;

-- Article 8: اعداد صحیح و عملیات روی آن‌ها
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>What Are Integers?</h2><p>Integers include all whole numbers: positive, negative, and zero. Understanding them is essential for 7th grade mathematics.</p><h2>Addition and Subtraction of Integers</h2><p>When adding integers with the same sign, add their absolute values and keep the sign. When signs differ, subtract the smaller absolute value from the larger and keep the sign of the larger.</p><h2>Multiplication and Division</h2><p>The product of two numbers with the same sign is positive. The product of two numbers with different signs is negative. The same rules apply to division.</p><h2>Number Line</h2><p>Using a number line helps visualize integer operations and is a great tool for beginners.</p><h2>Conclusion</h2><p>Integers form the basis for understanding negative numbers in real life, such as temperatures and elevations.</p>',
  'ps', '<h2>صحیح اعداد کوم دي؟</h2><p>صحیح اعداد ټول ټولیز شمیرې پوره کوي: مثبت، منفي، او صفر. د ۷م ټولګي ریاضي لپاره د دوی پوهیدل اړین دي.</p><h2>د صحیح اعدادو جمع او تفریق</h2><p>کله چې د ورته نښه اعداد جمع کوئ، مطلق قیمتونه یې جمع کړئ او نښه وساتئ. کله چې نښې توپیر ولري، کوچنی مطلق قیمت له لوی نه کم کړئ.</p><h2>ضرب او تقسیم</h2><p>د ورته نښه دوه شمیرو حاصل ضرب مثبت دی. د توپیر نښه دوه شمیرو حاصل ضرب منفي دی.</p><h2>پایله</h2><p>صحیح اعداد د واقعي ژوند کې د منفي شمیرو پوهیدو لپاره بنسټ جوړوي، لکه تودوخه او لوړوالی.</p>'
) WHERE id = 8;

-- Article 9: قوانین نیوتون به زبان ساده
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Newton''s Three Laws of Motion</h2><p>Sir Isaac Newton formulated three laws that describe how objects move. These laws are fundamental to classical mechanics and can be observed in everyday life.</p><h2>First Law: Law of Inertia</h2><p>An object at rest stays at rest, and an object in motion stays in motion unless acted upon by an external force. A ball on the ground does not move until someone kicks it.</p><h2>Second Law: F = ma</h2><p>Force equals mass times acceleration. A heavier object requires more force to accelerate at the same rate as a lighter one.</p><h2>Third Law: Action and Reaction</h2><p>For every action, there is an equal and opposite reaction. When you push against a wall, the wall pushes back with equal force.</p><h2>Real-Life Examples from Afghanistan</h2><p>A donkey cart on a flat road, a stone rolling down a hill, or a boat on a river — all demonstrate Newton''s laws in daily Afghan life.</p>',
  'ps', '<h2>د نیوټن درې قوانین</h2><p>سر ایزاک نیوټن درې قوانین جوړ کړل چې ښیي اشیاء څنګه حرکت کوي. دا قوانین د کلاسیکي مکانیک لپاره بنسټیز دي او ورځني ژوند کې لیدل کیدای شي.</p><h2>لومړی قانون: د جمود قانون</h2><p>یو ساکن شی ساکن پاتیږي، او یو متحرک شی متحرک پاتیږي تر هغه پورې چې بهرنی ځواک پرې ونه لګیږي.</p><h2>دویم قانون: F = ma</h2><p>ځواک د ډله او وچکتیا حاصل ضرب دی. یو درنه شی د مساوي وچکتیا لپاره ډیر ځواک غواړي.</p><h2>دریم قانون: عمل او عکس العمل</h2><p>د هر عمل لپاره مساوي او مخالف عکس العمل شته. کله چې دیوال ته ټک ووهئ، دیوال ورته ځواک سره ورته بیرته مقاومت کوي.</p><h2>د افغانستان له ژوند نه بیلګې</h2><p>یو کوره ماڼۍ پر مستقیم سړک، پر غونډۍ لاندې کوزیدونکی کاڼی، یا د سیند پر کښتۍ — ټول ورځني افغاني ژوند کې د نیوټن قوانین نندارتیا کوي.</p>'
) WHERE id = 9;

-- Article 10: دوره غزنویان — عصر طلایی افغانستان
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>The Ghaznavid Empire</h2><p>The Ghaznavid Empire (977–1186 CE) was one of the most powerful Islamic empires in Central and South Asia. Founded by Sabuktigin and reaching its peak under Sultan Mahmud of Ghazni, it was known for its cultural and military achievements.</p><h2>Cultural Golden Age</h2><p>Sultan Mahmud patronized scholars, poets, and scientists. The legendary poet Ferdowsi wrote parts of the Shahnameh during this era. Al-Biruni, the renowned scientist, accompanied Mahmud on expeditions to India.</p><h2>Legacy</h2><p>The Ghaznavid period left a lasting mark on Persian literature, Islamic architecture, and the cultural identity of Afghanistan. Ghazni was a major center of learning and civilization.</p>',
  'ps', '<h2>د غزنویانو امپراتوري</h2><p>د غزنویانو امپراتوري (۹۷۷–۱۱۸۶ م) د منځنۍ او سویلي اسیا کې له پیاوړو اسلامي امپراتوریو وه. د سبکتګین لخوا بنسټیزه شوه او د سلطان محمود غزنوي پر مهال خپل ذروه ته ورسیده.</p><h2>د کلتور طلایي دور</h2><p>سلطان محمود د پوهانو، شاعرانو، او ساینسپوهانو ملاتړ کاوه. د نامتو شاعر فردوسي شهنامه برخه پدې دور کې لیکل شوه. البیروني، نامتو ساینسپوه، د محمود سره هند ته سفرونو کې ملګری و.</p><h2>میراث</h2><p>د غزنویانو دور د پارسي ادب، اسلامي معماري، او د افغانستان د کلتوري هویت پر وخت سره اغیزه پریښوده.</p>'
) WHERE id = 10;

-- Article 11: رودخانه‌های اصلی افغانستان
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Major Rivers of Afghanistan</h2><p>Afghanistan has several important rivers that are vital for agriculture, drinking water, and daily life. The main rivers originate in the Hindu Kush mountains and flow in different directions.</p><h2>The Amu Darya</h2><p>The Amu Darya forms the northern border of Afghanistan with Central Asia. It is one of the longest rivers in the region and has historical significance as the ancient Oxus River.</p><h2>The Helmand River</h2><p>The Helmand is Afghanistan''s longest river, flowing southwest through the provinces of Helmand and Nimroz before reaching Iran. It irrigates vast agricultural lands.</p><h2>The Kabul River</h2><p>The Kabul River flows through Kabul and joins the Indus River in Pakistan. It is crucial for the capital''s water supply.</p><h2>Conclusion</h2><p>Rivers are the lifelines of Afghanistan. Their management and protection are essential for the country''s sustainable future.</p>',
  'ps', '<h2>د افغانستان اصلي سیندونه</h2><p>افغانستان ډیر مهم سیندونه لري چې د کرنې، د څښلو اوبو، او ورځني ژوند لپاره حیاتي دي. اصلي سیندونه د هندوکش غرونو کې پیدا کیږي او مختلفو لوریو ته بهیږي.</p><h2>د امو سیند</h2><p>د امو سیند د افغانستان شمالي پوله د منځنۍ اسیا سره جوړوي. دا د سیمې له اوږدو سیندونو یو دی.</p><h2>د هیرمند سیند</h2><p>هیرمند د افغانستان تر ټولو اوږد سیند دی چې د هلمند او نیمروز ولایتونو له لارې سویل لوڅي ته بهیږي.</p><h2>د کابل سیند</h2><p>د کابل سیند د کابل له لارې تیریږي او پاکستان کې د اباسین سیند سره یوځای کیږي.</p><h2>پایله</h2><p>سیندونه د افغانستان ژوندۍ نبض ده. د دوی اداره کول او ساتنه د هیواد د دوامداره راتلونکي لپاره اړینه ده.</p>'
) WHERE id = 11;

-- Article 12: جدول دوره‌ای عناصر
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>What Is the Periodic Table?</h2><p>The periodic table organizes all known chemical elements by their atomic number and properties. It was developed by Dmitri Mendeleev in 1869 and is one of the most important tools in chemistry.</p><h2>How to Read the Periodic Table</h2><p>Elements are arranged in rows (periods) and columns (groups). Elements in the same group have similar chemical properties. The atomic number tells you the number of protons in the nucleus.</p><h2>Key Groups</h2><p>Alkali metals, alkaline earth metals, transition metals, halogens, and noble gases are the main groups. Each has distinct properties and reactions.</p><h2>Tips for 8th Grade Students</h2><p>Focus on memorizing the first 20 elements, their symbols, and atomic numbers. Understanding trends in the table (like electronegativity and atomic radius) will help in future chemistry courses.</p>',
  'ps', '<h2>د دورې جدول ولې دی؟</h2><p>د دورې جدول ټول پیژندل شوي کیمیاوي عناصر د دوی اتومي شمیر او خاصیتونو پر بنسټ تنظیموي. دا د ۱۸۶۹ کال کې دیمیتري ميندلیف لخوا جوړ شو.</p><h2>د دورې جدول لوستل</h2><p>عناصر د قطارونو (دورې) او کالمونو (ډلې) کې تنظیم شوي دي. د ورته ډلې عناصر ورته کیمیاوي خاصیتونه لري.</p><h2>اصلي ډلې</h2><p>الکلي فلزات، الکالین ځمکه فلزات، لیږدیدونکي فلزات، هالوجنونه، او نجیب ګازونه اصلي ډلې دي.</p><h2>د ۸م ټولګي زده کوونکو لپاره لارښوونه</h2><p>لومړنیو ۲۰ عناصرو، د دوی سمبولونو، او اتومي شمیرو حفظولو ته پام وکړئ.</p>'
) WHERE id = 12;

-- Article 13: سلول — واحد پایه حیات
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>The Cell: Basic Unit of Life</h2><p>All living organisms are made of cells. The cell theory states that cells are the basic structural and functional units of all life forms.</p><h2>Types of Cells</h2><p>There are two main types: prokaryotic cells (like bacteria, without a nucleus) and eukaryotic cells (like plant and animal cells, with a nucleus).</p><h2>Cell Organelles</h2><p>Key organelles include the nucleus (control center), mitochondria (energy production), ribosome (protein synthesis), and cell membrane (protective barrier).</p><h2>Plant vs Animal Cells</h2><p>Plant cells have a cell wall, chloroplasts, and a large central vacuole, which animal cells lack. These differences relate to the different functions of plants and animals.</p><h2>Conclusion</h2><p>Understanding cells is the foundation of biology. Every disease, growth, and life process begins at the cellular level.</p>',
  'ps', '<h2>حجره: د ژوند بنسټیزه واحده</h2><p>ټول ژوندي موجودات له حجرو جوړ دي. د حجرې تیوري وايي چې حجرې د ټولو ژوندیو موجوداتو بنسټیزه جوړښتیزه او کاري واحده ده.</p><h2>د حجرو ډولونه</h2><p>دوه اصلي ډوله شته: پروکاریوتیکي حجرې (لکه باکتریا، بې نوکلیوسه) او یوکاریوتیکي حجرې (لکه د نبات او حیوان حجرې، له نوکلیوسه سره).</p><h2>د حجرې اندامکونه</h2><p>مهم اندامکونه پکې شامل دي: نوکلیوس (د کنترول مرکز)، مایتوکونډریا (د انرژۍ تولید)، ریبوزوم (د پروتین ترکیب)، او د حجرې غشا (ساتونکی خنډ).</p><h2>پایله</h2><p>د حجرو پوهیدل د بیولوژۍ بنسټ دی. هر ناروغي، وده، او د ژوند پروسه د حجروي کچه پیل کیږي.</p>'
) WHERE id = 13;

-- Article 14: ترفندهای یادگیری سریع واژگان انگلیسی
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Vocabulary Learning Strategies</h2><p>Building a strong English vocabulary requires consistent effort and smart strategies. Rote memorization alone is ineffective in the long term.</p><h2>Method 1: Contextual Learning</h2><p>Learn words in context — through sentences, stories, or real conversations. Words learned in context are retained far longer than isolated words.</p><h2>Method 2: Spaced Repetition</h2><p>Review vocabulary at increasing intervals. Apps like Anki use this technique to maximize long-term retention.</p><h2>Method 3: Word Families</h2><p>Learn related words together: happy, happiness, unhappy, happily. This multiplies your vocabulary exponentially.</p><h2>Method 4: Active Use</h2><p>Use new words in writing and speaking. The more you use a word, the more firmly it is embedded in your memory.</p><h2>Conclusion</h2><p>Vocabulary growth is a journey, not a sprint. Consistent daily learning of 5–10 words will result in thousands of new words over a year.</p>',
  'ps', '<h2>د واژه زده کړې ستراتیژۍ</h2><p>د پیاوړي انګلیسي واژگانو جوړول دوامداره هڅه او هوښیارانه ستراتیژۍ غواړي. یوازې حفظ کول اوږدمهاله کې اغیزناک نه دي.</p><h2>لومړی میتود: د متن له لارې زده کړه</h2><p>کلمې د متن کې زده کړئ — د جملو، کیسو، یا واقعي خبرو اترو له لارې.</p><h2>دویم میتود: د فاصلې تکرار</h2><p>واژه د زیاتیدونکو وقفو سره بیا کتنه وکړئ. د Anki غوندې اپلیکیشنونه دا تخنیک کاروي.</p><h2>دریم میتود: د کلمو کورنۍ</h2><p>اړونده کلمې سره زده کړئ: happy, happiness, unhappy, happily. دا ستاسو واژه ګانې مضاعفوي.</p><h2>پایله</h2><p>د واژگانو وده یو سفر دی. هره ورځ ۵-۱۰ کلمو ته دوامداره زده کړه به پر یو کال کې زرګونه نوې کلمې رامنځته کړي.</p>'
) WHERE id = 14;

-- Article 15: مقدمه‌ای بر حساب دیفرانسیل
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Introduction to Calculus</h2><p>Calculus is the mathematics of change. It consists of two main branches: differential calculus (derivatives) and integral calculus (integrals).</p><h2>What Is a Derivative?</h2><p>A derivative measures the rate of change of a function. For example, if a function describes position, its derivative describes velocity.</p><h2>Basic Rules</h2><p>Key derivative rules include: the power rule (d/dx of xⁿ = nxⁿ⁻¹), the product rule, the quotient rule, and the chain rule.</p><h2>Real-World Applications</h2><p>Derivatives are used in physics (velocity and acceleration), economics (marginal cost and profit), and engineering (optimization problems).</p><h2>Conclusion</h2><p>Calculus opens the door to advanced mathematics, physics, and engineering. A strong foundation in algebra and functions is essential before studying calculus.</p>',
  'ps', '<h2>د کالکولس پیژندنه</h2><p>کالکولس د بدلون ریاضي ده. دوه اصلي برخې لري: توپیري کالکولس (مشتقات) او انتگرالي کالکولس (انتگرالونه).</p><h2>مشتق ولې دی؟</h2><p>مشتق د یوې دندې د بدلون کچه اندازه کوي. که چیرې یوه دنده موقعیت انعکاسوي، د هغې مشتق سرعت انعکاسوي.</p><h2>اصلي قواعد</h2><p>د مشتق اصلي قواعد پکې شامل دي: د ځواک قاعده، د حاصل ضرب قاعده، د تقسیم قاعده، او د زنځیر قاعده.</p><h2>د واقعي نړۍ کارونه</h2><p>مشتقات فیزیک، اقتصاد، او انجنیري کې کارول کیږي.</p><h2>پایله</h2><p>کالکولس پرمختللي ریاضي، فیزیک، او انجنیري ته دروازه پرانیزي.</p>'
) WHERE id = 15;

-- Article 16: انرژی‌های تجدیدپذیر در افغانستان
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Renewable Energy in Afghanistan</h2><p>Afghanistan has enormous potential for renewable energy due to its geography — abundant sunshine, high winds, and fast-flowing rivers.</p><h2>Solar Energy</h2><p>Afghanistan receives over 300 sunny days per year in many provinces. Solar panels are already being used in rural areas for electricity and water pumping.</p><h2>Wind Energy</h2><p>The high-altitude passes and open plains of Afghanistan create favorable conditions for wind turbines, especially in the north and west.</p><h2>Hydropower</h2><p>Rivers like the Helmand and Amu Darya have significant hydropower potential. Several small dams are already generating electricity.</p><h2>Conclusion</h2><p>Developing renewable energy can reduce Afghanistan''s dependence on imports and provide clean electricity to millions of people in remote areas.</p>',
  'ps', '<h2>د افغانستان نوي وړانده انرژۍ</h2><p>افغانستان د خپل جغرافیه له امله — ډیرو لمریزو ورځو، لوړو بادونو، او چټکو سیندونو له امله — د نوي وړانده انرژۍ لپاره لوی ظرفیت لري.</p><h2>د لمر انرژي</h2><p>افغانستان ډیرو ولایتونو کې کلنۍ ۳۰۰ لمریزې ورځې ترلاسه کوي. د لیرو سیمو کې د برق او د اوبو د پمپولو لپاره د لمر پینلونه کارول کیږي.</p><h2>د باد انرژي</h2><p>د افغانستان لوړوالیزو لارو او پرانیستو میدانونو د باد توربینونو لپاره مناسب شرایط جوړوي.</p><h2>د اوبو بریښنا</h2><p>لکه د هیرمند او امو سیندونه د اوبو بریښنا لپاره د پام وړ ظرفیت لري.</p><h2>پایله</h2><p>د نوي وړانده انرژۍ پراختیا کولای شي د واردات پر وړاندې د افغانستان تکیه کمه کړي.</p>'
) WHERE id = 16;

-- Article 17: جنبش مشروطه‌خواهی در افغانستان
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>The Constitutional Movement in Afghanistan</h2><p>The constitutional movement in Afghanistan during the Amani period (1919–1929) was a significant attempt to modernize the country and introduce democratic governance.</p><h2>Amanullah Khan''s Reforms</h2><p>King Amanullah Khan introduced Afghanistan''s first constitution in 1923, abolished slavery, promoted education for women, and established modern schools and hospitals.</p><h2>Opposition and Resistance</h2><p>Conservative tribes and religious leaders opposed rapid modernization. The reforms led to tensions that ultimately contributed to Amanullah''s abdication in 1929.</p><h2>Legacy</h2><p>Despite its short duration, the constitutional movement laid important groundwork for later reform movements in Afghanistan and demonstrated the ongoing tension between tradition and modernity.</p>',
  'ps', '<h2>د افغانستان د مشروطیت غورځنګ</h2><p>د امانیه دور (۱۹۱۹-۱۹۲۹) کې د افغانستان د مشروطیت غورځنګ د هیواد د عصري کولو او دموکراتیک حکومتداري د معرفي کولو لپاره یو مهم هڅه وه.</p><h2>د امان الله خان اصلاحات</h2><p>شاه امان الله خان د ۱۹۲۳ کال کې د افغانستان لومړۍ اساسي قانون معرفي کړ، غلامي یې لغوه کړه، د ښځو لپاره یې تعلیم هڅاوه، او عصري ښوونځي او روغتیاگانې یې جوړې کړې.</p><h2>مخالفت او مقاومت</h2><p>مافوق قبایل او مذهبي مشران د چټک عصري کولو مخالفت کاوه. اصلاحاتو هغو تنشونو ته لار پرانیستله چې پای د امان الله د استعفا سبب شول.</p><h2>میراث</h2><p>د لنډ موده پرته هم، مشروطیت غورځنګ د افغانستان د وروستیو اصلاحي غورځنګونو لپاره مهم بنسټ کیښود.</p>'
) WHERE id = 17;

-- Article 18: ژنتیک و قوانین مندل
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Gregor Mendel and Genetics</h2><p>Gregor Mendel, an Austrian monk, discovered the basic principles of heredity through experiments with pea plants in the 1860s. His work forms the foundation of modern genetics.</p><h2>First Law: Law of Segregation</h2><p>Each individual has two alleles for each trait, and these separate during reproduction so that each gamete carries only one allele.</p><h2>Second Law: Law of Independent Assortment</h2><p>Genes for different traits are inherited independently of each other.</p><h2>Punnett Squares</h2><p>Punnett squares are used to predict the probability of offspring inheriting particular traits. They are a key tool in genetics for students.</p><h2>Dominant and Recessive Traits</h2><p>Dominant alleles mask recessive alleles. For a recessive trait to appear, an organism must have two copies of the recessive allele.</p>',
  'ps', '<h2>ګریګور مندل او جینیتیک</h2><p>ګریګور مندل، یو اتریشي راهب، د ۱۸۶۰ لسیزه کې د نخود نباتاتو سره آزمایښتونو له لارې د وراثت بنسټیزه اصول کشف کړل.</p><h2>لومړی قانون: د جلا کیدو قانون</h2><p>هر فرد د هر خاصیت لپاره دوه الیلونه لري، او دا د تولید پر مهال جلا کیږي ترڅو هر ګامیت یوازې یو الیل ولري.</p><h2>دویم قانون: د خپلواکه توزیع قانون</h2><p>د مختلفو خاصیتونو لپاره جینونه د یو بل تر خپلواکه وراثت ترلاسه کوي.</p><h2>د پانیت مربعونه</h2><p>د پانیت مربعونه د اولادونو د ځانګړو خاصیتونو د وراثت احتمال اټکل کولو لپاره کارول کیږي.</p><h2>غالب او مغلوب خاصیتونه</h2><p>غالب الیلونه مغلوب الیلونه پوښي. د یو مغلوب خاصیت د ښکاریدو لپاره موجود باید د مغلوب الیل دوه کاپۍ ولري.</p>'
) WHERE id = 18;

-- Article 19: چطور مقاله انگلیسی بنویسیم؟
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>How to Write a Five-Paragraph Essay</h2><p>The five-paragraph essay is the standard format for English writing exams and is widely used in academic settings. Mastering it is essential for university entrance exams.</p><h2>Structure</h2><p>Paragraph 1: Introduction with a hook and thesis statement. Paragraphs 2–4: Body paragraphs, each with a topic sentence, evidence, and analysis. Paragraph 5: Conclusion that restates the thesis and summarizes key points.</p><h2>Writing a Strong Thesis</h2><p>Your thesis statement is the backbone of your essay. It should be specific, arguable, and clearly state your position on the topic.</p><h2>Transitions and Cohesion</h2><p>Use transition words (however, furthermore, in contrast) to connect ideas and ensure your essay flows smoothly from one paragraph to the next.</p><h2>Common Mistakes</h2><p>Avoid starting sentences with "I think" or "In my opinion" in formal essays. Use evidence and logic instead of personal feelings.</p>',
  'ps', '<h2>د پنځه پاراګرافه مقاله لیکل</h2><p>د پنځه پاراګرافه مقاله د انګلیسي لیکنو امتحاناتو لپاره معیاري بڼه ده او د اکاډمیکو چاپیریالونو کې پراخه کارول کیږي.</p><h2>جوړښت</h2><p>۱ پاراګراف: د یوه اغیزناک مقدمه سره پیل او د مرکزي موضوع بیان. ۲-۴ پاراګرافونه: هر یو سره د موضوع جمله، شواهد، او تحلیل. ۵ پاراګراف: پایلې چې اصلي موضوع بیا بیانوي.</p><h2>قوي تیزیس لیکل</h2><p>ستاسو تیزیس جمله ستاسو مقاله د ستن ده. دا باید ځانګړی، د بحث وړ، او ستاسو موقف روښانه بیانه کړي.</p><h2>عامې غلطۍ</h2><p>رسمي مقالو کې د "زه فکر کوم" یا "زما د نظر لحاظ" سره د جملو پیل مه کوئ. د شخصي احساساتو پر ځای دلایل او منطق وکاروئ.</p>'
) WHERE id = 19;

-- Article 20: تغییرات آب‌وهوایی و تأثیر آن بر افغانستان
UPDATE article SET body = body || jsonb_build_object(
  'en', '<h2>Climate Change and Afghanistan</h2><p>Afghanistan is one of the countries most vulnerable to climate change, despite contributing very little to global greenhouse gas emissions. The impacts are already being felt across the country.</p><h2>Droughts and Water Scarcity</h2><p>Rising temperatures are accelerating glacier melt in the Hindu Kush, causing rivers to swell seasonally but dry up in the long term. Droughts are becoming more frequent and severe, threatening agriculture and food security.</p><h2>Floods and Landslides</h2><p>Erratic rainfall patterns are causing more intense flash floods and landslides, destroying crops, homes, and infrastructure.</p><h2>Impact on Agriculture</h2><p>With 80% of Afghans depending on agriculture, climate change poses a direct threat to livelihoods. Crop yields are declining, and traditional farming calendars are disrupted.</p><h2>What Can Be Done?</h2><p>Adaptation strategies include drought-resistant crops, water conservation techniques, reforestation, and climate-smart agriculture practices.</p>',
  'ps', '<h2>د آب وهوا بدلون او افغانستان</h2><p>افغانستان د نړۍ هغه هیوادونو کې یو دی چې تر ټولو زیات د آب وهوا بدلون خطر سره مخ دی، حتې که چیرې د نړیوالو ګازونو د خپریدو کې ډیره کمه برخه لري. اغیزې دمخه ټول هیواد کې محسوسیږي.</p><h2>وچکالي او د اوبو کمښت</h2><p>د تودوخې زیاتیدل د هندوکش کې د یخچالونو ویلیدل چټک کوي، سیندونه فصلي توره بهیږي خو اوږدمهاله وچیږي.</p><h2>سیلابونه او د ځمکې سریدل</h2><p>غیر منظمو بارانونو نمونو ډیرو چټکو سیلابونو او د ځمکې سریدلو لامل کیږي.</p><h2>پر کرنه اغیزه</h2><p>د ۸۰٪ افغانانو سره چې کرنه پرې ژوند کوي، آب وهوا بدلون د معاش سره سمه ګواښ ده.</p><h2>څه کیدای شي؟</h2><p>د تطابق ستراتیژۍ پکې د وچکالۍ مقاومت لرونکي محصولات، د اوبو ساتنه، بیا ځنګلول، او د آب وهوا هوښیارانه کرنه شامل دي.</p>'
) WHERE id = 20;

COMMIT;
